# Generated by Django 4.1.7 on 2023-03-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_city_country_person_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
